databases:
  - name: gamedashboard
    databaseName: gamedashboard
    user: gamedashboard

services:
  - type: web
    name: gamedashboard
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gamedashboard.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamedashboard
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4