databases:
  - name: gamedashapp
    databaseName: gamedashapp
    user: gamedashapp

services:
  - type: web
    name: gamedashapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gamedashapp.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamedashapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4